### ISSUE TITLE
쿠버네티스에 mosquitto 올리기

### ISSUE THREAD

**Issue by DongKeun94** [DongKeun94/Issue#3]
1. musma-iot 레포지토리 클론
2. musma-iot의 common에서 루트ca,cert 생성 , CERT 폴더에서 서버, 클라이언트용 cert,pem 생성
3. 생성된 키에서 kubectl create secrets generic  -o yaml > secret.yaml 
4.  mosquitto-deploy.yaml 작성해서 volume에 secret key 경로 mount
5.  이후 상세 내용은 명일 더 자세히 작성 !

**Comment by DongKeun94** [comment]
mosquitto-cluster.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mosquitto
  name: mosquitto
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      volumes:
      - name: mosquitto-cfg
        projected:
          sources:
          - secret:
              name: mosquitto-tls
              items:
              - key: ca-certificate
                path: ./CERTS/root-certs/ca.pem
              - key: server-certificate
                path: ./CERTS/cert.pem
              - key: server-key
                path: ./CERTS/cert-key.pem
              - key: acl-key
                path: ./acl-key
          - configMap:
              name: mosquitto-config
#             items:
#              - key: mosquitto.conf
#                path: mosquitto.conf
      - name: mosquitto-data
        emptyDir: {}
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: mqtt
          containerPort: 8883
        volumeMounts:
        - mountPath: /mosquitto/config
          name: mosquitto-cfg
          readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: test
spec:
  ports:
  - name: mqtt
    protocol: TCP
    port: 8883
    targetPort: 8883
  selector:
    app: mosquitto
  type: ClusterIP
```

mosquitto-config.yaml

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: mosquitto-config
  namespace: test
data:
  mosquitto.conf: |
    listener 8883
    # Mosquitto configuration file
    # cafile is mounted from a secret
    cafile /mosquitto/config/CERTS/root-certs/ca.pem
    # certfile is mounted from a secret
    certfile /mosquitto/config/CERTS/cert.pem
    # keyfile is mounted from a secret
    keyfile /mosquitto/config/CERTS/cert-key.pem
    # aclfile is mounted from a secret
    acl_file /mosquitto/config/acl-key
    tls_version tlsv1.2
    require_certificate true
    use_identity_as_username true
    # Disallow weak ciphers
    ciphers DEFAULT:!aNULL:!eNULL:!LOW:!EXPORT:!SSLv2:@STRENGTH

```

**Comment by DongKeun94** [comment]
volume mount path 부분 자세히 봐야함
```
mosquitto-cluster.yaml

containers:
      - name: mosquitto
        image: eclipse-mosquitto:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: mqtt
          containerPort: 8883
        volumeMounts:
        - mountPath: /mosquitto/config
          name: mosquitto-cfg
          readOnly: true
```
container volume mount에서 mountPath에 /mosquitto/config 에 하위 디렉토리를 하나 더 만들면 mosquitto.conf 파일이 
하나 더 생성 되는 경우가 발생 함 -> 내가 작성한 mosquitto-config.yaml 파일에 작성한 mosquitto.conf 파일이 생성된 컨테이너의
/mosquitto/config 밑에 하위 디렉토리 안에 들어가서 적용 안될수 있음

-- acl file은 topic과 user 맞춰서 하나 작성
```
# cli 사용해서 k8s secret 생성하는 yaml 파일 생성 후 secret 먼저 만들기
kubectl create secret generic mosquitto-tls \
  --namespace=test --from-file=ca-certificate=./CERTS/root-certs/ca.pen \
  --from-file=server-certificate=./CERTS/cert.pem \
  --from-file=server-key=./CERTS/cert-key.pem —from-file=acl-key=./CERTS/acl-key —dry-run=client -o yaml > “파일명.yaml”
```

secret이 만들어지면 config 그리고 cluster 순서대로 apply 해서 클러스터를 생성
